# Generated by Django 2.2.4 on 2019-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cnpj', models.CharField(max_length=15)),
                ('site', models.URLField(null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('profilePhoto', models.ImageField(upload_to='company_profile_photo')),
            ],
        ),
    ]
