# Generated by Django 2.2.4 on 2019-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=60),
        ),
    ]
